In [13]:
import numpy as np
from sklearn import svm, tree, ensemble
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 读取数据
def load_data():
    data = []
    labels = []
    for i in range(1, 6):
        for gesture in ['circle', 'wave', 'comeHere', 'goAway']:
            file_path = './data/' + gesture + '_' + str(i) + '.csv'
            # 读取文件
            with open(file_path, 'r') as f:
                lines = f.readlines()[1:]
                for line in lines:
                    # 去除时间列
                    values = line.strip().split(',')[1:]
                    # 选取前三列作为特征
                    features = list(map(float, values[:3]))
                    data.append(features)
                    labels.append(gesture)
    return np.array(data), np.array(labels)

# 切分数据集
def split_dataset(X, y, train_ratio=0.7, val_ratio=0.1):
    total_samples = len(X)
    train_size = int(total_samples * train_ratio)
    val_size = int(total_samples * val_ratio)
    test_size = total_samples - train_size - val_size
    
    indices = np.random.permutation(total_samples)
    train_indices = indices[:train_size]
    val_indices = indices[train_size:train_size+val_size]
    test_indices = indices[train_size+val_size:]
    
    X_train, y_train = X[train_indices], y[train_indices]
    X_val, y_val = X[val_indices], y[val_indices]
    X_test, y_test = X[test_indices], y[test_indices]
    
    return X_train, y_train, X_val, y_val, X_test, y_test

# 训练模型
def train_model(X_train, y_train, X_val, y_val, algorithm='svm', **kwargs):
    if algorithm == 'svm':
        model = svm.SVC(**kwargs)
    elif algorithm == 'decision_tree':
        model = tree.DecisionTreeClassifier(**kwargs)
    elif algorithm == 'random_forest':
        model = ensemble.RandomForestClassifier(**kwargs)
    else:
        raise ValueError('Invalid algorithm: ' + algorithm)
    
    # 训练模型
    model.fit(X_train, y_train)
    
    # 在验证集上评估模型
    y_val_pred = model.predict(X_val)
    val_acc = accuracy_score(y_val, y_val_pred)
    print('Validation accuracy: {:.4f}'.format(val_acc))
    
    return model

# 在测试集上评估模型
def test_model(model, X_test, y_test):
    y_test_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)
    print('Test accuracy: {:.4f}'.format(test_acc))
    
    print('Classification report:')
    print(classification_report(y_test, y_test_pred))
    
    print('Confusion matrix:')
    print(confusion_matrix(y_test, y_test_pred))
    
    # 输出测试集的文件名和预测结果的对比
#     print('测试集文件名\t\t预测结果')
#     for i in range(len(X_test)):
#         file_index = np.where(np.logical_and(X_test[i][0] == X[:, 0], X_test[i][1] == X[:, 1], X_test[i][2] == X[:, 2]))[0][0]
#         print('{}\t\t{}'.format(y[file_index], y_test_pred[i]))

if __name__ == '__main__':
    X, y = load_data()
    X_train, y_train, X_val, y_val, X_test, y_test = split_dataset(X, y)
    
    # 训练和评估SVM模型
    print('Training SVM model...')
    svm_model = train_model(X_train, y_train, X_val, y_val, algorithm='svm', kernel='linear')
    
    # 在测试集上评估SVM模型
    print('Testing SVM model...')
    test_model(svm_model, X_test, y_test)

    # 训练和评估决策树模型
    print('Training decision tree model...')
    dt_model = train_model(X_train, y_train, X_val, y_val, algorithm='decision_tree', criterion='entropy')
    
    # 在测试集上评估决策树模型
    print('Testing decision tree model...')
    test_model(dt_model, X_test, y_test)
    
    # 训练和评估随机森林模型
    print('Training random forest model...')
    rf_model = train_model(X_train, y_train, X_val, y_val, algorithm='random_forest', n_estimators=100)
    
    # 在测试集上评估随机森林模型
    print('Testing random forest model...')
    test_model(rf_model, X_test, y_test)



Training SVM model...
Validation accuracy: 0.3542
Testing SVM model...
Test accuracy: 0.3628
Classification report:
              precision    recall  f1-score   support

      circle       0.34      0.34      0.34      1496
    comeHere       0.40      0.53      0.46      1369
      goAway       0.39      0.26      0.31      1302
        wave       0.31      0.31      0.31      1279

    accuracy                           0.36      5446
   macro avg       0.36      0.36      0.36      5446
weighted avg       0.36      0.36      0.36      5446

Confusion matrix:
[[515 298 280 403]
 [317 722  16 314]
 [481 312 338 171]
 [192 456 230 401]]
Training decision tree model...
Validation accuracy: 0.6730
Testing decision tree model...
Test accuracy: 0.6732
Classification report:
              precision    recall  f1-score   support

      circle       0.67      0.68      0.68      1496
    comeHere       0.66      0.65      0.65      1369
      goAway       0.60      0.61      0.61      1302
 

In [12]:
# import numpy as np
# from sklearn import svm, tree, ensemble
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# # 读取数据
# def load_data():
#     data = []
#     labels = []
#     for i in range(1, 6):
#         for gesture in ['circle', 'wave', 'comeHere', 'goAway']:
#             file_path = './data/' + gesture + '_' + str(i) + '.csv'
#             # 读取文件
#             with open(file_path, 'r') as f:
#                 lines = f.readlines()[1:]
#                 for line in lines:
#                     # 去除时间列
#                     values = line.strip().split(',')[1:]
#                     # 选取前三列作为特征
#                     features = list(map(float, values[:3]))
#                     data.append(features)
#                     labels.append(gesture)
#     return np.array(data), np.array(labels)

# # 切分数据集
# def split_dataset(X, y, train_ratio=0.7, val_ratio=0.1):
#     total_samples = len(X)
#     train_size = int(total_samples * train_ratio)
#     val_size = int(total_samples * val_ratio)
#     test_size = total_samples - train_size - val_size
    
#     indices = np.random.permutation(total_samples)
#     train_indices = indices[:train_size]
#     val_indices = indices[train_size:train_size+val_size]
#     test_indices = indices[train_size+val_size:]
    
#     X_train, y_train = X[train_indices], y[train_indices]
#     X_val, y_val = X[val_indices], y[val_indices]
#     X_test, y_test = X[test_indices], y[test_indices]
    
#     return X_train, y_train, X_val, y_val, X_test, y_test

# # 训练模型
# def train_model(X_train, y_train, X_val, y_val, algorithm='svm', **kwargs):
#     if algorithm == 'svm':
#         model = svm.SVC(**kwargs)
#     elif algorithm == 'decision_tree':
#         model = tree.DecisionTreeClassifier(**kwargs)
#     elif algorithm == 'random_forest':
#         model = ensemble.RandomForestClassifier(**kwargs)
#     else:
#         raise ValueError('Invalid algorithm: ' + algorithm)
    
#     # 训练模型
#     model.fit(X_train, y_train)
    
#     # 在验证集上评估模型
#     y_val_pred = model.predict(X_val)
#     val_acc = accuracy_score(y_val, y_val_pred)
#     print('Validation accuracy: {:.4f}'.format(val_acc))
    
#     return model

# # 在测试集上评估模型
# def test_model(model, X_test, y_test):
#     y_test_pred = model.predict(X_test)
#     test_acc = accuracy_score(y_test, y_test_pred)
#     print('Test accuracy: {:.4f}'.format(test_acc))
    
#     print('Classification report:')
#     print(classification_report(y_test, y_test_pred))
    
#     print('Confusion matrix:')
#     print(confusion_matrix(y_test, y_test_pred))
    
#     # 输出测试集的文件名和预测结果的对比
#     print('测试集文件名\t\t预测结果')
#     for i in range(len(X_test)):
#         file_index = np.where(np.logical_and(X_test[i][0] == X[:, 0], X_test[i][1] == X[:, 1], X_test[i][2] == X[:, 2]))[0][0]
#         print('{}\t\t{}'.format(y[file_index], y_test_pred[i]))

# if __name__ == '__main__':
#     X, y = load_data()
#     X_train, y_train, X_val, y_val, X_test, y_test = split_dataset(X, y)
    
#     # 训练和评估SVM模型
#     print('Training SVM model...')
#     svm_model = train_model(X_train, y_train, X_val, y_val, algorithm='svm', kernel='linear')
    
#     # 在测试集上评估SVM模型
#     print('Testing SVM model...')
#     test_model(svm_model, X_test, y_test)

#     # 训练和评估决策树模型
#     print('Training decision tree model...')
#     dt_model = train_model(X_train, y_train, X_val, y_val, algorithm='decision_tree', criterion='entropy')
    
#     # 在测试集上评估决策树模型
#     print('Testing decision tree model...')
#     test_model(dt_model, X_test, y_test)
    
#     # 训练和评估随机森林模型
#     print('Training random forest model...')
#     rf_model = train_model(X_train, y_train, X_val, y_val, algorithm='random_forest', n_estimators=100)
    
#     # 在测试集上评估随机森林模型
#     print('Testing random forest model...')
#     test_model(rf_model, X_test, y_test)


Training SVM model...
Validation accuracy: 0.3758
Testing SVM model...
Test accuracy: 0.3819
Classification report:
              precision    recall  f1-score   support

      circle       0.37      0.41      0.39      1489
    comeHere       0.41      0.55      0.47      1386
      goAway       0.42      0.26      0.32      1339
        wave       0.32      0.28      0.30      1232

    accuracy                           0.38      5446
   macro avg       0.38      0.38      0.37      5446
weighted avg       0.38      0.38      0.37      5446

Confusion matrix:
[[615 325 265 284]
 [310 767  11 298]
 [498 342 351 148]
 [234 452 199 347]]
测试集文件名		预测结果
comeHere		comeHere
comeHere		wave
goAway		circle
circle		wave
wave		comeHere
wave		circle
wave		wave
goAway		comeHere
goAway		circle
goAway		comeHere
goAway		wave
circle		comeHere
circle		circle
wave		wave
goAway		circle
comeHere		comeHere
goAway		wave
comeHere		comeHere
goAway		comeHere
goAway		comeHere
comeHere		circle
circle		wave
circl

wave		wave
circle		circle
comeHere		comeHere
comeHere		wave
comeHere		goAway
circle		circle
wave		wave
wave		wave
circle		circle
comeHere		circle
circle		circle
comeHere		circle
circle		wave
goAway		circle
circle		wave
goAway		goAway
comeHere		circle
circle		wave
goAway		circle
circle		comeHere
circle		circle
comeHere		goAway
circle		circle
comeHere		comeHere
goAway		wave
comeHere		comeHere
goAway		wave
goAway		goAway
circle		comeHere
circle		circle
goAway		circle
circle		goAway
goAway		comeHere
goAway		goAway
comeHere		comeHere
wave		comeHere
circle		circle
goAway		circle
wave		goAway
wave		comeHere
circle		circle
goAway		wave
circle		goAway
goAway		goAway
circle		comeHere
circle		circle
goAway		goAway
wave		comeHere
circle		goAway
goAway		goAway
comeHere		circle
circle		circle
goAway		comeHere
circle		circle
circle		circle
goAway		wave
comeHere		circle
circle		circle
comeHere		comeHere
circle		goAway
goAway		comeHere
comeHere		wave
wave		wave
goAway		circle
wave		circle
circle		comeH

goAway		goAway
circle		wave
wave		circle
comeHere		comeHere
circle		goAway
circle		circle
comeHere		comeHere
circle		goAway
comeHere		circle
wave		wave
circle		goAway
goAway		comeHere
comeHere		comeHere
goAway		comeHere
circle		goAway
comeHere		wave
goAway		goAway
goAway		circle
wave		wave
circle		wave
circle		wave
circle		comeHere
wave		comeHere
wave		wave
circle		circle
circle		goAway
goAway		goAway
goAway		comeHere
goAway		goAway
goAway		goAway
wave		wave
comeHere		comeHere
circle		circle
goAway		comeHere
goAway		comeHere
circle		goAway
circle		wave
comeHere		circle
circle		wave
wave		comeHere
circle		wave
circle		circle
circle		goAway
comeHere		comeHere
comeHere		wave
goAway		goAway
wave		comeHere
circle		circle
goAway		comeHere
wave		comeHere
circle		comeHere
comeHere		wave
goAway		goAway
circle		circle
wave		goAway
comeHere		wave
comeHere		comeHere
comeHere		comeHere
comeHere		comeHere
wave		wave
comeHere		wave
goAway		circle
circle		wave
goAway		circle
circle		goAway
goAway		wav

Validation accuracy: 0.6774
Testing decision tree model...
Test accuracy: 0.6781
Classification report:
              precision    recall  f1-score   support

      circle       0.67      0.70      0.68      1489
    comeHere       0.65      0.66      0.65      1386
      goAway       0.64      0.63      0.64      1339
        wave       0.76      0.74      0.75      1232

    accuracy                           0.68      5446
   macro avg       0.68      0.68      0.68      5446
weighted avg       0.68      0.68      0.68      5446

Confusion matrix:
[[1035  184  159  111]
 [ 189  909  210   78]
 [ 186  219  842   92]
 [ 139   90   96  907]]
测试集文件名		预测结果
comeHere		circle
comeHere		comeHere
goAway		goAway
circle		circle
wave		wave
wave		wave
wave		comeHere
goAway		comeHere
goAway		goAway
goAway		goAway
goAway		circle
circle		goAway
circle		circle
wave		wave
goAway		goAway
comeHere		goAway
goAway		wave
comeHere		comeHere
goAway		goAway
goAway		goAway
comeHere		circle
circle		comeHere
cir

circle		circle
comeHere		comeHere
circle		circle
goAway		circle
goAway		goAway
wave		circle
comeHere		circle
wave		wave
circle		goAway
circle		circle
circle		circle
comeHere		comeHere
comeHere		comeHere
comeHere		goAway
comeHere		comeHere
comeHere		comeHere
wave		wave
goAway		goAway
circle		circle
comeHere		comeHere
comeHere		comeHere
goAway		goAway
wave		wave
circle		circle
comeHere		comeHere
comeHere		wave
wave		goAway
comeHere		comeHere
comeHere		goAway
circle		goAway
goAway		goAway
comeHere		comeHere
circle		circle
wave		wave
comeHere		comeHere
wave		wave
goAway		goAway
comeHere		comeHere
goAway		goAway
goAway		goAway
wave		wave
comeHere		wave
circle		circle
circle		goAway
comeHere		comeHere
wave		wave
goAway		comeHere
wave		wave
comeHere		comeHere
goAway		comeHere
goAway		comeHere
wave		wave
circle		goAway
goAway		goAway
comeHere		comeHere
wave		comeHere
comeHere		comeHere
goAway		goAway
comeHere		comeHere
wave		wave
circle		circle
wave		wave
circle		circle
comeHere		comeHere
come

circle		circle
comeHere		comeHere
comeHere		comeHere
circle		circle
comeHere		comeHere
wave		circle
comeHere		comeHere
wave		circle
comeHere		comeHere
wave		wave
wave		wave
wave		wave
circle		circle
goAway		circle
goAway		goAway
goAway		comeHere
wave		wave
comeHere		comeHere
comeHere		comeHere
circle		circle
comeHere		comeHere
wave		goAway
comeHere		circle
comeHere		comeHere
circle		comeHere
wave		wave
circle		circle
comeHere		goAway
comeHere		comeHere
circle		circle
circle		circle
circle		circle
comeHere		circle
circle		goAway
circle		goAway
circle		wave
goAway		comeHere
circle		circle
goAway		circle
goAway		goAway
goAway		goAway
circle		comeHere
comeHere		comeHere
goAway		wave
circle		circle
wave		wave
circle		goAway
comeHere		goAway
comeHere		comeHere
circle		circle
comeHere		comeHere
circle		circle
wave		comeHere
goAway		circle
comeHere		comeHere
wave		wave
goAway		comeHere
wave		wave
comeHere		comeHere
circle		circle
circle		circle
circle		comeHere
comeHere		comeHere
circle		goAwa

Validation accuracy: 0.7359
Testing random forest model...
Test accuracy: 0.7444
Classification report:
              precision    recall  f1-score   support

      circle       0.72      0.78      0.75      1489
    comeHere       0.72      0.75      0.73      1386
      goAway       0.74      0.68      0.70      1339
        wave       0.82      0.77      0.79      1232

    accuracy                           0.74      5446
   macro avg       0.75      0.74      0.75      5446
weighted avg       0.75      0.74      0.74      5446

Confusion matrix:
[[1158  158  104   69]
 [ 138 1041  147   60]
 [ 177  173  906   83]
 [ 132   76   75  949]]
测试集文件名		预测结果
comeHere		circle
comeHere		comeHere
goAway		goAway
circle		circle
wave		wave
wave		wave
wave		wave
goAway		goAway
goAway		circle
goAway		circle
goAway		circle
circle		circle
circle		circle
wave		wave
goAway		goAway
comeHere		circle
goAway		goAway
comeHere		comeHere
goAway		goAway
goAway		comeHere
comeHere		circle
circle		comeHere
circl

comeHere		comeHere
wave		goAway
goAway		circle
circle		circle
comeHere		wave
wave		comeHere
circle		circle
wave		wave
goAway		goAway
goAway		goAway
circle		circle
wave		wave
circle		comeHere
goAway		comeHere
comeHere		comeHere
circle		circle
circle		circle
wave		comeHere
goAway		goAway
circle		circle
wave		wave
comeHere		comeHere
wave		comeHere
goAway		circle
circle		wave
comeHere		comeHere
circle		circle
goAway		goAway
comeHere		comeHere
wave		wave
goAway		goAway
goAway		comeHere
circle		circle
comeHere		comeHere
circle		circle
comeHere		comeHere
comeHere		circle
wave		wave
goAway		goAway
wave		wave
wave		goAway
comeHere		comeHere
comeHere		wave
wave		circle
goAway		circle
goAway		circle
goAway		goAway
wave		wave
goAway		goAway
circle		circle
wave		wave
comeHere		comeHere
comeHere		comeHere
goAway		goAway
comeHere		comeHere
wave		wave
circle		circle
wave		wave
goAway		goAway
comeHere		goAway
wave		wave
comeHere		comeHere
comeHere		comeHere
circle		circle
wave		wave
comeHere		goAway
wa

comeHere		comeHere
wave		wave
comeHere		comeHere
circle		circle
wave		wave
wave		wave
comeHere		wave
circle		circle
goAway		goAway
wave		circle
circle		circle
wave		wave
comeHere		goAway
comeHere		comeHere
goAway		goAway
goAway		circle
goAway		goAway
wave		wave
goAway		goAway
wave		wave
goAway		wave
comeHere		wave
circle		circle
comeHere		comeHere
goAway		goAway
goAway		goAway
comeHere		comeHere
comeHere		comeHere
goAway		goAway
circle		comeHere
wave		goAway
goAway		goAway
goAway		circle
goAway		comeHere
goAway		goAway
wave		wave
comeHere		comeHere
circle		circle
wave		wave
comeHere		comeHere
wave		wave
circle		circle
wave		wave
comeHere		comeHere
wave		circle
comeHere		comeHere
wave		wave
comeHere		wave
comeHere		goAway
comeHere		circle
circle		circle
comeHere		goAway
goAway		circle
comeHere		wave
wave		wave
wave		circle
goAway		goAway
goAway		goAway
wave		wave
comeHere		goAway
circle		circle
goAway		goAway
goAway		goAway
comeHere		comeHere
circle		circle
comeHere		wave
comeHere		come

comeHere		comeHere
comeHere		comeHere
comeHere		comeHere
goAway		goAway
comeHere		comeHere
goAway		goAway
comeHere		comeHere
comeHere		comeHere
circle		circle
comeHere		comeHere
goAway		goAway
goAway		goAway
wave		wave
goAway		comeHere
comeHere		comeHere
goAway		goAway
circle		comeHere
comeHere		comeHere
circle		circle
circle		wave
circle		wave
comeHere		comeHere
goAway		goAway
circle		comeHere
comeHere		comeHere
wave		wave
circle		circle
comeHere		comeHere
circle		circle
goAway		comeHere
wave		wave
wave		wave
goAway		goAway
goAway		goAway
circle		circle
comeHere		comeHere
circle		circle
comeHere		goAway
goAway		goAway
wave		wave
goAway		circle
goAway		goAway
comeHere		comeHere
goAway		circle
comeHere		comeHere
comeHere		comeHere
circle		circle
comeHere		comeHere
circle		circle
circle		circle
wave		wave
goAway		goAway
comeHere		comeHere
goAway		goAway
circle		circle
comeHere		comeHere
circle		circle
circle		wave
comeHere		comeHere
goAway		goAway
comeHere		comeHere
goAway		goAway
wave		

In [18]:
import os
import numpy as np
from sklearn import svm, tree, ensemble
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 读取数据
def load_data():
    data = []
    labels = []
    for i in range(1, 6):
        for gesture in ['circle', 'wave', 'comeHere', 'goAway']:
            file_path = './data/' + gesture + '_' + str(i) + '.csv'
            # 读取文件
            with open(file_path, 'r') as f:
                lines = f.readlines()[1:]
                for line in lines:
                    # 去除时间列
                    values = line.strip().split(',')[1:]
                    # 选取前三列作为特征
                    features = list(map(float, values[:3]))
                    data.append(features)
                    labels.append(gesture)
    return np.array(data), np.array(labels)

# 读取测试数据
def load_test_data():
    data = []
    labels = []
    for i in range(1, 6):
        for gesture in ['circle_test', 'wave_test','comeHere_test','goAway_test']:
            file_path = './data_test/' + gesture + '_' + str(i) + '.csv'
            # 读取文件
            with open(file_path, 'r') as f:
                lines = f.readlines()[1:]
                # 选取前三列作为特征
                features = []
                for line in lines:
                    values = line.strip().split(',')[1:4]
                    features.append(list(map(float, values)))
                data.append(features)
                labels.append(gesture[:-5])
    return np.array(data), np.array(labels)

# 切分数据集
def split_dataset(X, y, train_ratio=0.7, val_ratio=0.1):
    total_samples = len(X)
    train_size = int(total_samples * train_ratio)
    val_size = int(total_samples * val_ratio)
    test_size = total_samples - train_size - val_size
    
    indices = np.random.permutation(total_samples)
    train_indices = indices[:train_size]
    val_indices = indices[train_size:train_size+val_size]
    test_indices = indices[train_size+val_size:]
    
    X_train, y_train = X[train_indices], y[train_indices]
    X_val, y_val = X[val_indices], y[val_indices]
    X_test, y_test = X[test_indices], y[test_indices]
    
    return X_train, y_train, X_val, y_val, X_test, y_test

# 训练模型
def train_model(X_train, y_train, X_val, y_val, algorithm='svm', **kwargs):
    if algorithm == 'svm':
        model = svm.SVC(**kwargs)
    elif algorithm == 'decision_tree':
        model = tree.DecisionTreeClassifier(**kwargs)
    elif algorithm == 'random_forest':
        model = ensemble.RandomForestClassifier(**kwargs)
    else:
        raise ValueError('Invalid algorithm: ' + algorithm)
    
    # 训练模型
    model.fit(X_train, y_train)
    
    # 在验证集上评估模型
    y_val_pred = model.predict(X_val)
    val_acc = accuracy_score(y_val, y_val_pred)
    print('Validation accuracy: {:.4f}'.format(val_acc))
    
    return model

# 在测试集上评估模型
def test_model(model, X_test, y_test):
    y_test_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)
    print('Test accuracy: {:.4f}'.format(test_acc))
    
    print('Classification report:')
    print(classification_report(y_test, y_test_pred))
    
    print('Confusion matrix:')
    print(confusion_matrix(y_test, y_test_pred))
    
    # 输出测试集的文件名和预测结果的对比
    print('测试集文件名\t\t预测结果')
    for i, gesture in enumerate(['circle_test', 'wave_test','comeHere_test','goAway_test']):
        for j in range(1, 6):
            file_path = './data_test/' + gesture + '_' + str(j) + '.csv'
            with open(file_path, 'r') as f:
                lines = f.readlines()[1:]
                # 选取前三列作为特征
                features = []
                for line in lines:
                    values = line.strip().split(',')[1:4]
                    features.append(list(map(float, values)))
                # 将所有样本作为一个整体进行预测
                prediction = model.predict(np.array(features))
                # 打印预测结果和文件名的对比
                print('{}\t\t{}'.format(file_path, prediction[0]))

if __name__ == '__main__':
    X, y = load_data()
    X_train, y_train, X_val, y_val, X_test, y_test = split_dataset(X, y)
    
    # 训练和评估SVM模型
    print('Training SVM model...')
    svm_model = train_model(X_train, y_train, X_val, y_val, algorithm='svm', kernel='linear')
    
    # 在测试集上评估SVM模型
    print('Testing SVM model...')
    test_model(svm_model, X_test, y_test)

    # 训练和评估决策树模型
    print('Training decision tree model...')
    dt_model = train_model(X_train, y_train, X_val, y_val, algorithm='decision_tree', criterion='entropy')
    
    # 在测试集上评估决策树模型
    print('Testing decision tree model...')
    test_model(dt_model, X_test, y_test)
    
    # 训练和评估随机森林模型
    print('Training random forest model...')
    rf_model = train_model(X_train, y_train, X_val, y_val, algorithm='random_forest', n_estimators=100)
    
    # 在测试集上评估随机森林模型
    print('Testing random forest model...')
    test_model(rf_model, X_test, y_test)




Training SVM model...
Validation accuracy: 0.3619
Testing SVM model...
Test accuracy: 0.3674
Classification report:
              precision    recall  f1-score   support

      circle       0.34      0.37      0.35      1488
    comeHere       0.39      0.53      0.45      1366
      goAway       0.42      0.28      0.33      1318
        wave       0.32      0.29      0.31      1274

    accuracy                           0.37      5446
   macro avg       0.37      0.37      0.36      5446
weighted avg       0.37      0.37      0.36      5446

Confusion matrix:
[[548 318 274 348]
 [348 718  12 288]
 [495 308 363 152]
 [209 480 213 372]]
测试集文件名		预测结果
./data_test/circle_test_1.csv		comeHere
./data_test/circle_test_2.csv		comeHere
./data_test/circle_test_3.csv		comeHere
./data_test/circle_test_4.csv		comeHere
./data_test/circle_test_5.csv		comeHere
./data_test/wave_test_1.csv		comeHere
./data_test/wave_test_2.csv		comeHere
./data_test/wave_test_3.csv		comeHere
./data_test/wave_test_4.csv